import {
    BellIcon,
    CalendarIcon,
    FileTextIcon,
    GlobeIcon,
    InputIcon,
} from "@radix-ui/react-icons";

const Skeleton = () => (
    <div className="flex flex-1 w-full h-full min-h-[6rem] rounded-xl bg-gradient-to-br from-neutral-200 dark:from-neutral-900 dark:to-neutral-800 to-neutral-100"></div>
);

export const features = [
    {
        Icon: FileTextIcon,
        name: "Save your files",
        description: "We automatically save your files as you type.",
        href: "/",
        cta: "Learn more",
        header: <Skeleton />,
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        width: 200,
        height: 400,
    },
    {
        Icon: InputIcon,
        name: "Full text search",
        description: "Search through all your files in one place.",
        href: "/",
        cta: "Learn more",
        header: <Skeleton />,
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        width: 400,
        height: 200,
    },
    {
        Icon: GlobeIcon,
        name: "Multilingual",
        description: "Supports 100+ languages and counting.",
        href: "/",
        cta: "Learn more",
        header: <Skeleton />,
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        width: 300,
        height: 300,
    },
    {
        Icon: CalendarIcon,
        name: "Calendar",
        description: "Use the calendar to filter your files by date.",
        href: "/",
        cta: "Learn more",
        header: <Skeleton />,
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        width: 300,
        height: 400,
    },
    {
        Icon: BellIcon,
        name: "Notifications",
        description:
            "Get notified when someone shares a file or mentions you in a comment.",
        href: "/",
        cta: "Learn more",
        header: <Skeleton />,
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        width: 400,
        height: 300,
    },


    {
        Icon: FileTextIcon,
        name: "Save your files2",
        description: "We automatically save your files as you type.",
        href: "/",
        cta: "Learn more",
        header: <Skeleton />,
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        width: 200,
        height: 400,
    },
    {
        Icon: InputIcon,
        name: "Full text search2",
        description: "Search through all your files in one place.",
        href: "/",
        cta: "Learn more",
        header: <Skeleton />,
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        width: 400,
        height: 200,
    },
    {
        Icon: GlobeIcon,
        name: "Multilingual2",
        description: "Supports 100+ languages and counting.",
        href: "/",
        cta: "Learn more",
        header: <Skeleton />,
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        width: 300,
        height: 300,
    },
    {
        Icon: CalendarIcon,
        name: "Calendar2",
        description: "Use the calendar to filter your files by date.",
        href: "/",
        cta: "Learn more",
        header: <Skeleton />,
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        width: 300,
        height: 400,
    },
    {
        Icon: BellIcon,
        name: "Notifications2",
        description:
            "Get notified when someone shares a file or mentions you in a comment.",
        href: "/",
        cta: "Learn more",
        header: <Skeleton />,
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        width: 400,
        height: 300,
    },
];
